## Лабораторная работа №1 | Вариант 7

Выполнил: Коваль М. М8О-211Б-23

### 1. Numpy

In [2]:
import numpy as np

1. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

```python
nan
False
False
nan
True
False
```

2. Создайте матрицу 5х5 со значениями 1, 2, 3, 4 ниже диагонали

In [90]:
answer = np.repeat(np.arange(5), 5).reshape((5, 5))
np.tril(answer, -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 4, 0]])

3. Создайте матрицу 8х8 и заполните ее паттерном шахматной доски

In [129]:
row = np.arange(8).reshape(-1, 1)
col = np.arange(8)
matrix = (row + col) % 2
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. Умножте матрицу 5х3 и 3х2 (матричное умножение)

In [39]:
first_array = np.arange(15).reshape((5, 3))
second_array = np.arange(6).reshape((3, 2))
print(f"1)\n{first_array}\n2)\n{second_array}\n")
a_1 = np.dot(first_array, second_array)
a_2 = first_array.dot(second_array)
a_3 = first_array@second_array
print(f"answer:\n{a_1}")
equality = [np.equal(a_1, a_2) & np.equal(a_2, a_3)]
np.all(equality)

1)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
2)
[[0 1]
 [2 3]
 [4 5]]

answer:
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


np.True_

5. Как получить все даты, соответствующие июлю 2016 года?

In [41]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

6. Создайте матрицу размером 5х5 со случайными значениями строк в диапазоне от 0 до 4

In [44]:
seed = 52
rng = np.random.default_rng(seed=seed)
rng.integers(low=0, high=5, size=25).reshape(5, 5)

array([[4, 3, 1, 2, 2],
       [2, 3, 0, 1, 2],
       [1, 4, 4, 1, 0],
       [0, 1, 1, 4, 4],
       [2, 4, 0, 2, 1]])

7. Создайте вектор размером 10 со значениями в диапазоне от $(0, 1)$

In [57]:
v = rng.random(10) 
v, v.shape

(array([0.81207239, 0.14960361, 0.86472171, 0.56359034, 0.43984039,
        0.01032552, 0.18337542, 0.27824419, 0.9283804 , 0.38486705]),
 (10,))

8. Выведите минимальное и максимальное представимое значение для каждого скалярного типа numpy

In [66]:
types = [np.int8, np.int16, np.int32, np.int64, np.float16, np.float32, np.float64]
for dtype in types:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
    else:
        info = np.finfo(dtype)

    print(f"{dtype.__name__} max = {info.max}, min = {info.min}")

int8 max = 127, min = -128
int16 max = 32767, min = -32768
int32 max = 2147483647, min = -2147483648
int64 max = 9223372036854775807, min = -9223372036854775808
float16 max = 65504.0, min = -65504.0
float32 max = 3.4028234663852886e+38, min = -3.4028234663852886e+38
float64 max = 1.7976931348623157e+308, min = -1.7976931348623157e+308


9. Как отсортировать массив по n-му столбцу?

In [ ]:
?

([(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)],
 array([2, 0, 4, 6, 5, 3, 1]))

10. Как определить, есть ли в данном двумерном массиве пустые столбцы?

In [145]:
array = np.array([
    [0, 1, np.nan, -1],
    [0, 2, np.nan, -1],
    [0, 3, np.nan, -1]
])

empty_columns = np.all((array == 0) | np.isnan(array) | (array == -1), axis=0)
empty_columns

array([ True, False,  True,  True])

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Набор данных для изучения зависимости различных параметров тела человека.

Файл: `data.csv`

```
Height (cm) - рост человека в сантиметрах
Weight (kg) - вес человека в килограммах
Blood Pressure (s/d) - кровяное давление(systolic/diastolic) в mmHg.
Cholesterol Level (mg/dL) - уровень холестерина milligrams per deciliter.
BMI - Body Mass Index, рассчитывается по весу и росту.
Blood Glucose Level (mg/dL) - уровень глюкозы в крови milligrams per deciliter.
Bone Density (g/cm²) - плотность костной массы grams per square centimeter.
Vision Sharpness - четкость зрения от 0 (полностью размыто) до 100 (идеально).
Hearing Ability (dB) - способность воспринимать звуки в dB.
Physical Activity Level - уровень физической активности 'Low', 'Moderate', или 'High'.
Smoking Status - статус курильщика 'Never', 'Former', и 'Current'.
Alcohol Consumption - частота принятия алкоголя.
Diet - тип диеты. Категоризован на 'Balanced', 'High Protein', 'Low Carb', и т.п.
Chronic Diseases - наличие хронических заболеваний (e.g., diabetes, hypertension).
Medication Use - использование медикаментов.
Family History - наличие в семейном анамнезе возрастных заболеваний.
Cognitive Function - самооценка когнитивных функций по шкале от 0 (плохая) до 100 (отличная).
Mental Health Status - самооценка состояния психического здоровья по шкале от 0 (плохое) до 100 (отличное).
Sleep Patterns - среднее кол-во сна за ночь.
Stress Levels - самооценка уровня стресса по шкале от 0 (низкий) до 100 (высокий).
Pollution Exposure - воздействие загрязнения, измеряемое в произвольных единицах измерения.
Sun Exposure - среднее время пребывания на солнце в часах в неделю.
Education Level - уровень образования.
Income Level - доход в USD.
```

In [2]:
import pandas as pd

In [21]:
# Load dataset here

1. Какой средний вес людей представленных в наборе данных?

2. Сбалансировано ли соотношение мужчин и женщин в наборе данных?

3. Правда ли, что люди с высоким уровнем стресса имеют более высокое кровяное давление, чем те, кто не подвержен стрессу

4. Правда ли, что уровень холестерина у мужчин и женщин отличается?

5. Правда ли, что с возрастом женщины имеют свойство оценивать свои когнитивные способности хуже, чем в юности (порог юности - 30 лет, женщина в возрасте - 60 лет+)

6. Влияет ли физическая активность на вес в возрасте более 50 лет?

7. Сравните минимальный вес мужчин с высоким и низким заработком

8. Правда ли, что у людей с индексом массы тела больше 75го перцентиля встречаются хронические заболевания чаще, чем у людей с индесом массы тела в переделах от 30 до 60 перцентиля?

9. Правда ли, что люди с высоким уровнем дохода имеют больший уровень физической активности, чем люди с низким доходом

10. Какая доля мужчин с высокой частотой пребывания на солнце имеет высокий заработок?

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Визуализируйте частоту встречаемых хронических заболеваний

2. Как связана оценка собственных когнитивных функций с уровнем стресса?

3. Визуализируйте как зависит вес от роста человека

4. Постройте box plot отображающий распределение уровня стресса у людей с различным уровнем дохода

5. Постройте круговую диаграмму отображающую как ментальное здоровье связано с паттернами сна

6. Имеет ли связь зрение и способность слышать звуки на высоких частотах? Ответьте на вопрос - какая зависимость между ними и предположите почему зависимость именно такая?

7. Красиво визуализируйте как связаны между собой уровень дохода, когнитивные способности и уровень стресса*

\* Задание на доп. балл